name: Pull Request Webhook notification

on:
  pull_request:
    types: [opened, synchronized, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send PR notification to webhook
        # GitHub Secret에 저장된 URL을 환경 변수로 설정
        env:
          WEBHOOK_URL: ${{ secrets.MY_WEBHOOK_URL }}
        run: |
          curl -X POST \
            -H "Content-Type: application/json"\
            -d '{
            "repository_owner": "${{github.repository_owner}}",
            "repository_name": "${{github.event.repository.name}}",
            "pull_request_number": "${{github.event.pull_request.number}}",
            "pull_request_url":"${{github.event.pull_request.html_url}}",
            "action":"${{github.event.action}}",
            "pull_request_title":"${{github.event.pull_request.title}}",
            "pull_request_author":"${{github.event.pull_request.user.login}}"
            }' \
            "https://vktmpwxdcwznmu8dcnpeh1gv.hooks.n8n.cloud/webhook-test/e7923797-309b-4448-afb4-99834c318d3c/webhook"
