name: Pull Request Webhook notification

on:
  pull_request:
    types: [opened, synchronized, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send PR notification to webhook
        run: |
          curl -X POST \
            -H "Content-Type: application/json"\
            -d '{
            "repository_owner": "${{github.repository_owner}}",
            "repository_name": "${{github.event.repository.name}}",
            "pull_request_number": "${{github.event.pull_request.number}}",
            "pull_request_url":"${{github.event.pull_request.html_url}}",
            "action":"${{github.event.action}}",
            "pull_request_title":${{github.event.pull_request.title}},
            "pull_request_author":"${{github.event.pull_request.user.login}}"
            }'  \
            https://vktmpwxdcwznmu8dcnpeh1gv.hooks.n8n.cloud/webhook-test/d45b7727-d519-432b-9ff7-a8546842fd5c/webhook
